import BlurFade from "@/components/magicui/blur-fade";
import Section from "@/components/section";
import { Card, CardContent } from "@/components/ui/card";
import { Brain, Shield, Zap } from "lucide-react";

const problems = [
  {
    title: "Scientific Quality is Declining",
    description:
      "Research literature struggle to ensure scientific quality. Paper mills and predatory journal is getting more common. Wild citation and abuse of metrics let to the phenomenon known as GoodHart's Law.",
    icon: Brain,
  },
  {
    title: "Peer Review Process Getting Slower",
    description:
      "Traditional scientific publication system methods are too slow, struggling to find and incentivize peer reviewer to attest publication quality. Editors are overwhelm with rapidly increasing volume of manuscripts, some of which are fraudulent and possibly generated by AI.",
    icon: Zap,
  },
  {
    title: "Reproducibility Crisis",
    description:
      "With increasing innacuracy and mild fraud threats, research are becoming less and less reproducible. This led to a waste of taxpayer and other enterprise money that goes into research funding.",
    icon: Shield,
  },
];

export default function Component() {
  return (
    <Section
      title="Problem"
      subtitle="Peer Review Crisis is Real. The Aggregated Quality of Scientific Outputs is Declining."
    >
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
        {problems.map((problem, index) => (
          <BlurFade key={index} delay={0.2 + index * 0.2} inView>
            <Card className="bg-background border-none shadow-none">
              <CardContent className="p-6 space-y-4">
                <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
                  <problem.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-xl font-semibold">{problem.title}</h3>
                <p className="text-muted-foreground">{problem.description}</p>
              </CardContent>
            </Card>
          </BlurFade>
        ))}
      </div>
    </Section>
  );
}
